site_name: Manual de Especialidades
site_description: Manual de Especialidades em Markdown
site_author: Lucas Magno Zimmer
repo_url: https://github.com/lucksma96/manual-de-especialidades
theme:
  name: material
  user_color_mode_toggle: auto
  locale: pt_BR
  language: pt-BR
nav:
  - Início: index.md
  - Introdução: 'A Introdução/A Introdução.md'
  - ADRA: 'ADRA/ADRA.md'
  - Artes e Habilidades Manuais: 'Artes e Habilidades Manuais/Artes e Habilidades Manuais.md'
  - Atividades Agrícolas e Afins: 'Atividades Agrícolas e Afins/Atividades Agrícolas e Afins.md'
  - Atividades Missionárias e Comunitárias: 'Atividades Missionárias e Comunitárias/Atividades Missionárias e Comunitárias.md'
  - Atividades Profissionais: 'Atividades Profissionais/Atividades Profissionais.md'
  - Atividades Recreativas: 'Atividades Recreativas/Atividades Recreativas.md'
  - Ciência e Saúde: 'Ciência e Saúde/Ciência e Saúde.md'
  - Estudo da Natureza: 'Estudo da Natureza/Estudo da Natureza.md'
  - Habilidades Domésticas: 'Habilidades Domésticas/Habilidades Domésticas.md'
  - Mestrados: 'Mestrados/Mestrados.md'
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      toc_depth: 2
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
plugins:
  - offline